# Generated by Django 4.2.1 on 2023-05-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_rename_numero_juzgado_juzgado_juzgado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='juzgado',
            field=models.ForeignKey(blank=True, limit_choices_to={'juzgado__in': [1, 2, 3]}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.juzgado'),
        ),
    ]
