# Generated by Django 4.2.1 on 2023-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_alter_expediente_juzgado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juzgado',
            old_name='juzgado',
            new_name='numero_juzgado',
        ),
        migrations.AlterField(
            model_name='expediente',
            name='juzgado',
            field=models.IntegerField(choices=[(1, 'Juzgado 1'), (2, 'Juzgado 2'), (3, 'Juzgado 3')]),
        ),
    ]
