# Generated by Django 4.2.1 on 2023-05-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_rename_juzgado_juzgado_numero_juzgado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='juzgado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.juzgado'),
        ),
    ]
