# Generated by Django 4.2.1 on 2023-05-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_alter_evidencia_descripcion_alter_expediente_juzgado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juzgado',
            name='numero_juzgado',
            field=models.IntegerField(choices=[(1, 'Juzgado 1'), (2, 'Juzgado 2'), (3, 'Juzgado 3')], unique=True),
        ),
    ]
